"""Initial migration

Revision ID: 1cecc2d16dce
Revises:
Create Date: 2025-09-13 15:55:22.578291

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1cecc2d16dce'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'commands',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('received_command', sa.String(), nullable=False),
        sa.Column('executed_command', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'PENDING',
                'EXECUTING',
                'COMPLETED',
                'FAILED',
                name='command_status_enum',
            ),
            nullable=False,
        ),
        sa.Column('stopped_by_obstacle', sa.Boolean(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'positions',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('coord_x', sa.Integer(), nullable=False),
        sa.Column('coord_y', sa.Integer(), nullable=False),
        sa.Column(
            'direction',
            sa.Enum('NORTH', 'EAST', 'SOUTH', 'WEST', name='position_direction_enum'),
            nullable=False,
        ),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('command_id', sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ['command_id'],
            ['commands.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('positions')
    op.drop_table('commands')
    # ### end Alembic commands ###
